### ISSUE TITLE
Round countdown (display mode)

### ISSUE THREAD

**Issue by StolkArjen** [nodeGame/nodegame#142]
I don't know if the option is deprecated, but the countdown on the VisualRound widget seems not fully supported yet/anymore. Here's how to reproduce it: 

this.visualRound = node.widgets.append('VisualRound', header, {displayMode: ['COUNT_DOWN_ROUNDS']}); 

ng@0.0.0 - 17:41:0:687 > error - 0.0.0@17:41:0> http://localhost:8080/javascripts/nodegame-full.js 56863,20: TypeError: undefined is not an object (evaluating 'options.toTotal')

For comparison, the following works fine, showing default behavior:

this.visualRound = node.widgets.append('VisualRound', header, {displayMode: ['COUNT_UP_ROUNDS_TO_TOTAL']});

**Comment by shakty** [comment]
This is the issue I have fixed recently in dev...or at least I thought so, in fact I had forgotten to push. Please pull it again and let me know if it solved.

**Comment by StolkArjen** [comment]
It's not urgent (for me at least), but unfortunately the same issue seems still present, after updating:

From https://github.com/nodeGame/nodegame-widgets
   aed4132..b0ce40d  master     -> origin/master
Updating aed4132..b0ce40d
Fast-forward
 build/nodegame-widgets.js     | 86 ++++++++++++++++++++++++++++++++++---------
 build/nodegame-widgets.min.js |  2 +-
 widgets/ChoiceTable.js        | 83 ++++++++++++++++++++++++++++++++---------
 widgets/VisualRound.js        |  3 +-
 4 files changed, 137 insertions(+), 37 deletions(-)

**Comment by shakty** [comment]
Have rebuilt nodeGame client files after updating? node launcher -b widgets
Also please check that your browser has not cached the old version of
nodeGame. This happens a lot actually

Am Fr., 22. Mai 2020 um 20:59 Uhr schrieb StolkArjen <
notifications@github.com>:

**Comment by StolkArjen** [comment]
Issue solved. Indeed, clearing caches was necessary.

**Comment by StolkArjen** [comment]
On a related note, and I'm probably over-engineering this, what would be
your suggested approach for creating a new "Level" counter in the header? I
was thinking of using the content of the VisualRound widget, feed it with
information from the game ("node.game.level", which increases as players'
performance improves), and place it on the header's right hand side. The
potential issue I foresee is that, unlike for Round or Stage, information
of node.game.level doesn't exist at game initiation. Put differently, where
do variables like curRound and totRound typically get defined in the
pipeline - or is it not necessary to go that deep?

**Comment by shakty** [comment]
Why don't you use the VisualStage widget?
https://github.com/nodeGame/nodegame/wiki/VisualStage-Widget-v5
The preprocess function is what you are looking for.
To get the tot rounds variable:
node.game.plot.stager.sequence[node.player.stage.stage -1].num;




Am Fr., 22. Mai 2020 um 23:11 Uhr schrieb StolkArjen <
notifications@github.com>:

> On a related note, and I'm probably over-engineering this, what would be
> your suggested approach for creating a new "Level" counter in the header? I
> was thinking of using the content of the VisualRound widget, feed it with
> information from the game ("node.game.level", which increases as players'
> performance improves), and place it on the header's right hand side. The
> potential issue I foresee is that, unlike for Round or Stage, information
> of node.game.level doesn't exist at game initiation. Put differently, where
> do variables like curRound and totRound typically get defined in the
> pipeline - or is it not necessary to go that deep?
>

**Comment by StolkArjen** [comment]
Thanks for that pointer. The VisualStage seems much more manageable in
terms of sheer lines of code.

**Comment by shakty** [comment]
I think we fixed this. If not, feel free to reopen.
